#Contents of this file must be an exact copy of constants.go!

UnitCreated           = "A"
CreatorNotReady       = "B"
CreatorProcessingUnit = "C"
SendingUnitToCreator  = "D"
AddPreunits           = "E"
PreunitReady          = "F"
UnitAdded             = "G"
ReadyToAdd            = "H"
DuplicatedUnits       = "I"
DuplicatedPreunits    = "J"
UnknownParents        = "K"
NewTimingUnit         = "L"
OwnUnitOrdered        = "M"
LinearOrderExtended   = "N"
UnitOrdered           = "O"
SentUnit              = "P"
PreunitReceived       = "Q"
SyncStarted           = "R"
SyncCompleted         = "S"
GetInfo               = "T"
SendInfo              = "U"
GetUnits              = "V"
SendUnits             = "W"
PreblockProduced      = "Y"
NewEpoch              = "a"
EpochEnd              = "b"
SkippingEpoch         = "c"
ServiceStarted        = "d"
ServiceStopped        = "e"
GotWTK                = "f"
CreatorFinished       = "g"
ForkDetected          = "h"
MissingRandomBytes    = "i"
InvalidControlHash    = "j"
InvalidEpochProof     = "k"
InvalidCreator        = "l"
FreezedParent         = "m"
FutureLastTiming      = "n"
UnableToRetrieveEpoch = "o"
RequestOverload       = "p"

# Event     = "E"
# FreshSent = "F"
# FreshRecv = "G"
# Memory    = "M"
# Hash      = "#"
# Lvl       = "Q"
Sent              = "A"
Recv              = "B"
Creator           = "C"
ID                = "D"
Epoch             = "E"
ControlHash       = "F"
Height            = "H"
ISID              = "I"
WTKShareProviders = "J"
WTKThreshold      = "K"
LogLevel          = "L"
Message           = "M"
Size              = "N"
OSID              = "O"
PID               = "P"
Level             = "Q"
Round             = "R"
Service           = "S"
Time              = "T"

CreateService    = 0
OrderService     = 1
SyncService      = 2
ValidateService  = 3
MemLogService    = 4
GossipService    = 5
FetchService     = 6
MCService        = 7
RMCService       = 8
AlertService     = 9
AdderService     = 10

Genesis = "genesis"
